### PR TITLE
Fixed Module build failed (close #18)

### LINKED ISSUE #18: Module build failed: SyntaxError: Unexpected token
When I try build, show this error

```
ERROR in ./src/index.js
Module build failed: SyntaxError: Unexpected token (8:16)

  6 | import './styles/app.scss';
  7 |
> 8 | ReactDOM.render(<App />, document.getElementById('app'));
    |                 ^
```

### PR DESCRIPTION
**Pull request by edgardmessias**
Without update the library, this the minimal setup

### CODE REVIEW

**Comment by FZambia** [comment]
@edgardmessias thanks, I already started updating dependencies and adding `airbnb` eslint configuration, please give me some time to finish it - it also involves many improvements throughout source code so the final result should be more idiomatic than current code base. I will send separate pr soon, in case of failure will go with this one. OK?

**Comment by edgardmessias** [comment]
Nice!!

**Comment by FZambia** [comment]
@edgardmessias could you please try https://github.com/centrifugal/web/pull/21 - does `add_eslint` branch works for you?

**Comment by edgardmessias** [comment]
@FZambia , working fine here.

**Pull request closed without merging**
